version: '3'

services:
  backend:
    build: ./flask-backend
    ports:
      - '5000:5000'
    networks:
      - app-network

  frontend:
    build: ./react-frontend
    ports:
      - '3000:3000'
    networks:
      - app-network
    depends_on:
      - backend

networks:
  app-network:
    driver: bridge
